import type { Metadata } from "next";
{{css_import}}
export const metadata: Metadata = {
  title: "{{project_name}}",
  description: "Generated by create-ruxum-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
